#!/bin/bash
# bootstep-memory.sh — Summarize codebase to MEMORY.md when missing
# Explores code structure only (not docs), generates project memory

set -euo pipefail

cd "${1:-$(pwd)}"

OUTPUT=".claude/MEMORY.md"

# Don't overwrite existing
[ -f "$OUTPUT" ] && exit 0

# Generate from codebase exploration
cat > "$OUTPUT" << EOF
# Project Memory

**Last Updated:** $(date +%Y-%m-%d)
**Generated by:** bootstep-memory.sh

## Project Overview

$(basename "$PWD") - $(grep -m1 '^description' Cargo.toml 2>/dev/null | cut -d'"' -f2 || echo "No description")

## Architecture (from src/)

$(find src -name '*.rs' -type f 2>/dev/null | head -20 | while read f; do
    echo "- $f"
done)

## Key Components

- Detected from: Cargo.toml, src/ structure

## Build & CI

- Quality gate: make ci
- Build: cargo build --all-features

## Exclusions

- .git/, target/, .gemini/, .qwen/, .learnings/, secrets/

## Work Log

### $(date +%Y-%m-%d)
- Bootstrapped memory from codebase exploration
EOF

echo "Bootstrapped $OUTPUT"