name: Stale

on:
  schedule:
    - cron: '361 4 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs within 7 days.'
          stale-pr-message: 'This PR has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs within 7 days.'
          days-before-stale: 60
          days-before-close: 7
          stale-issue-label: 'status/stale'
          exempt-issue-labels: 'status/wip,type/bug'
          stale-pr-label: 'status/stale'